### ISSUE TITLE
请问是否考虑将图片居中显示这样更加美观

### ISSUE THREAD

**Issue by shixiaocaia** [aircloud/hexo-theme-aircloud#108]
尝试修改aircloud.css,发现并没有生效。
```css
.post-content p img {
  width: 80%;
  margin: 0 auto;
}

```
