### ISSUE TITLE
目录过长的话，toc 显示不完全

### ISSUE THREAD

**Issue by hqweay** [aircloud/hexo-theme-aircloud#22]
如果目录过长，效果类似这样：
![default](https://user-images.githubusercontent.com/23608642/46711123-8ccca400-cc7d-11e8-996d-8219e4ec9625.png)

屏幕外还有目录显示不出来...

很喜欢这个主题！感谢！

希望作者能修复下。

PS：
我自己直接在 css 上修改了一下
```css
/* toc.css */
.toc-item > .toc-child{
  display: none;
}
.toc-article li.active > .toc-child {
  display: block;
}
.toc-article li:hover > .toc-child {
  display: block;
}
```
效果如下（大概够用）
![default](https://user-images.githubusercontent.com/23608642/46711066-3a8b8300-cc7d-11e8-836d-ba3a7f47947a.png)
