### ISSUE TITLE
comment配置

### ISSUE THREAD

**Issue by Phoeby2618** [aircloud/hexo-theme-aircloud#52]
通过gitment方式配置评论功能，在login时一直显示“Loding comments”。请问除了更改id和secret，还有哪里需要配置的吗

**Comment by tea9** [comment]
可以用下gitalk
可以参考 添加下面截图代码
https://github.com/tea9/hexo-theme-aircloud/blob/master/layout/layout.ejs
![image](https://user-images.githubusercontent.com/39117901/63137373-8e3acb80-c008-11e9-95f0-9d24d2a25ead.png)

_config.yml
```
comment:
  type: gitalk
  id: your-id-created-by-https://github.com/settings/applications/new
  secret: your-secret-created-by-https://github.com/settings/applications/new
  owner: aircloud
  repo: hexo-aircloud-blog
```
