### ISSUE TITLE
赞赏按钮失效，似乎是.contains('hide')没有生效

### ISSUE THREAD

**Issue by Aixsnow** [aircloud/hexo-theme-aircloud#94]
我发现index.js中的.contains都是灰色的，似乎没有生效，按钮按了也没反应
```
if(donateButton) {
    donateButton.addEventListener('click', () => {
        
        if (donateImgContainer.classList.contains('hide')) {
            donateImgContainer.classList.remove('hide')
        } else {
            donateImgContainer.classList.add('hide')
        }
    })

    donateImg.src = donateImg.dataset.src
}
```

**Comment by Aixsnow** [comment]
反复对比demo找到原因了，要使用赞赏，还得在_config.yml里加上
```
    # The following content is not recommended to modify
    # 搜索数据文件路径设置，不建议改动：
    search:
        path: search.json
        field: post
```
